language: php

php:
  - 7.0

sudo: false

matrix:
  fast_finish: true

cache:
  apt: true

before_install:
  - echo $TRAVIS_PHP_VERSION
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - make prepare

addons:
  apt:
    packages:
      - nginx-extras
      - realpath

notifications:
  email:
    - benjaminfranzke@gmail.com

install:
  - make setup

script:
  - make check
  - cat /tmp/error.log
  - cat /tmp/access.log
