language: php

php:
  - 7.0

sudo: false

matrix:
  fast_finish: true

cache:
  apt: true

before_install:
  - echo $TRAVIS_PHP_VERSION
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi
  - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh -O .travis/assert.sh
  - wget http://gordalina.github.io/cachetool/downloads/cachetool.phar -O .travis/cachetool.phar
  - chmod +x .travis/cachetool.phar

addons:
  apt:
    packages:
      - nginx-extras
      - realpath

notifications:
  email:
    - benjaminfranzke@gmail.com

install:
  - .travis/install-nginx.sh

script:
  - export HOST='http://localhost:8088'
  - .travis/run-tests.sh
  - cat /tmp/error.log
  - cat /tmp/access.log
